# Generated by Django 5.2 on 2026-06-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Короткое описание"),
                ),
                (
                    "long_description",
                    models.TextField(blank=True, verbose_name="Длинное описание"),
                ),
                ("lat", models.FloatField(verbose_name="Широта")),
                ("lng", models.FloatField(verbose_name="Долгота")),
            ],
        ),
    ]
