# Generated by Django 5.2 on 2026-06-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="places", verbose_name="Изображение"),
                ),
                ("position", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="places.place",
                        verbose_name="Место",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
