# Generated by Django 5.2 on 2026-06-20 20:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="long_description",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Длинное описание"),
        ),
    ]
